// Sample data for the demo
export const sampleInternships = [
  {
    id: 1,
    title: 'Software Development Intern',
    company: 'TechVasavi Solutions',
    employer: 'Rajesh Kumar',
    location: 'Remote',
    type: 'Full-time',
    duration: '3 months',
    stipend: '$1,500/month',
    skills: ['React', 'Node.js', 'JavaScript', 'Git'],
    description: 'Join our development team to build modern web applications. You will work on real projects, collaborate with senior developers, and gain hands-on experience with cutting-edge technologies.',
    requirements: 'Currently pursuing a degree in Computer Science or related field. Basic knowledge of web development.',
    postedDate: '2026-03-15',
    deadline: '2026-04-30',
    status: 'open',
    applicants: 12,
    positions: 3,
  },
  {
    id: 2,
    title: 'Data Analytics Intern',
    company: 'DataBridge Corp',
    employer: 'Priya Reddy',
    location: 'New York, NY',
    type: 'Part-time',
    duration: '6 months',
    stipend: '$1,200/month',
    skills: ['Python', 'SQL', 'Tableau', 'Excel'],
    description: 'Analyze large datasets to derive actionable insights for our clients. You will work with our analytics team on real business problems and develop your data analysis skills.',
    requirements: 'Familiarity with Python or R. Basic statistics knowledge preferred.',
    postedDate: '2026-03-10',
    deadline: '2026-04-15',
    status: 'open',
    applicants: 8,
    positions: 2,
  },
  {
    id: 3,
    title: 'Marketing & Social Media Intern',
    company: 'NRIVA Foundation',
    employer: 'Lakshmi Devi',
    location: 'Remote',
    type: 'Part-time',
    duration: '4 months',
    stipend: 'Unpaid (Volunteer)',
    skills: ['Social Media', 'Content Writing', 'Canva', 'Marketing'],
    description: 'Help NRIVA expand its digital presence and engage with the community through social media campaigns, content creation, and event promotion.',
    requirements: 'Strong communication skills. Experience with social media platforms.',
    postedDate: '2026-03-20',
    deadline: '2026-05-15',
    status: 'open',
    applicants: 5,
    positions: 2,
  },
  {
    id: 4,
    title: 'Cloud Engineering Intern',
    company: 'CloudNine Technologies',
    employer: 'Venkat Rao',
    location: 'San Francisco, CA',
    type: 'Full-time',
    duration: '3 months',
    stipend: '$2,000/month',
    skills: ['Azure', 'AWS', 'Docker', 'Linux'],
    description: 'Work with our cloud infrastructure team to design, deploy, and maintain cloud solutions for enterprise clients.',
    requirements: 'Pursuing CS/IT degree. Basic understanding of cloud computing concepts.',
    postedDate: '2026-03-01',
    deadline: '2026-03-31',
    status: 'closed',
    applicants: 20,
    positions: 2,
  },
  {
    id: 5,
    title: 'Graphic Design Intern',
    company: 'CreativeVasavi Studio',
    employer: 'Anita Sharma',
    location: 'Remote',
    type: 'Part-time',
    duration: '3 months',
    stipend: '$800/month',
    skills: ['Adobe Photoshop', 'Illustrator', 'Figma', 'UI/UX'],
    description: 'Create visual assets for marketing campaigns, product designs, and brand materials. Work closely with the creative director.',
    requirements: 'Portfolio of design work. Proficiency in Adobe Creative Suite.',
    postedDate: '2026-03-18',
    deadline: '2026-05-01',
    status: 'open',
    applicants: 7,
    positions: 1,
  },
  {
    id: 6,
    title: 'Finance & Accounting Intern',
    company: 'NRIVA Foundation',
    employer: 'Suresh Patel',
    location: 'Houston, TX',
    type: 'Full-time',
    duration: '6 months',
    stipend: '$1,300/month',
    skills: ['QuickBooks', 'Excel', 'Financial Analysis', 'Accounting'],
    description: 'Support the finance team with bookkeeping, financial reporting, and budget analysis for the non-profit organization.',
    requirements: 'Pursuing a degree in Finance, Accounting, or Business Administration.',
    postedDate: '2026-02-28',
    deadline: '2026-04-01',
    status: 'filled',
    applicants: 15,
    positions: 1,
  },
]

export const sampleApplications = [
  {
    id: 1,
    internshipId: 1,
    internshipTitle: 'Software Development Intern',
    company: 'TechVasavi Solutions',
    applicantName: 'Arjun Naidu',
    email: 'arjun.naidu@email.com',
    phone: '(555) 123-4567',
    university: 'University of Texas at Austin',
    major: 'Computer Science',
    graduationYear: '2027',
    gpa: '3.7',
    appliedDate: '2026-03-16',
    status: 'under_review',
    resume: 'arjun_naidu_resume.pdf',
    coverLetter: 'I am excited to apply for the Software Development Intern position...',
  },
  {
    id: 2,
    internshipId: 1,
    internshipTitle: 'Software Development Intern',
    company: 'TechVasavi Solutions',
    applicantName: 'Sneha Reddy',
    email: 'sneha.r@email.com',
    phone: '(555) 234-5678',
    university: 'Georgia Tech',
    major: 'Information Technology',
    graduationYear: '2026',
    gpa: '3.9',
    appliedDate: '2026-03-17',
    status: 'shortlisted',
    resume: 'sneha_reddy_resume.pdf',
    coverLetter: 'As a senior IT student at Georgia Tech, I bring...',
  },
  {
    id: 3,
    internshipId: 2,
    internshipTitle: 'Data Analytics Intern',
    company: 'DataBridge Corp',
    applicantName: 'Vikram Patel',
    email: 'vikram.p@email.com',
    phone: '(555) 345-6789',
    university: 'NYU',
    major: 'Data Science',
    graduationYear: '2027',
    gpa: '3.5',
    appliedDate: '2026-03-12',
    status: 'accepted',
    resume: 'vikram_patel_resume.pdf',
    coverLetter: 'With a strong foundation in statistics and Python...',
  },
  {
    id: 4,
    internshipId: 3,
    internshipTitle: 'Marketing & Social Media Intern',
    company: 'NRIVA Foundation',
    applicantName: 'Meera Krishnan',
    email: 'meera.k@email.com',
    phone: '(555) 456-7890',
    university: 'UCLA',
    major: 'Communications',
    graduationYear: '2026',
    gpa: '3.6',
    appliedDate: '2026-03-21',
    status: 'pending',
    resume: 'meera_krishnan_resume.pdf',
    coverLetter: 'As an active NRIVA youth member, I am passionate about...',
  },
  {
    id: 5,
    internshipId: 5,
    internshipTitle: 'Graphic Design Intern',
    company: 'CreativeVasavi Studio',
    applicantName: 'Ravi Teja',
    email: 'ravi.t@email.com',
    phone: '(555) 567-8901',
    university: 'SCAD',
    major: 'Graphic Design',
    graduationYear: '2027',
    gpa: '3.8',
    appliedDate: '2026-03-19',
    status: 'rejected',
    resume: 'ravi_teja_resume.pdf',
    coverLetter: 'My passion for visual storytelling drives me to...',
  },
]

export const chapters = [
  'Alaska', 'Albany', 'Arizona', 'Atlanta', 'Austin', 'Baltimore',
  'Boston', 'Charlotte', 'Chicago', 'Cincinnati', 'Cleveland',
  'Colorado', 'Columbus', 'Connecticut', 'Dallas', 'Detroit',
  'Houston', 'Indianapolis', 'Kansas City', 'Los Angeles',
  'Michigan', 'Minnesota', 'New Jersey', 'New York', 'North Carolina',
  'Ohio', 'Oklahoma', 'Oregon', 'Philadelphia', 'Pittsburgh',
  'San Francisco', 'Seattle', 'St. Louis', 'Tampa', 'Virginia', 'Washington DC'
]
