// Seed script - run this once from the browser console or a temp page
// to populate Firestore with test data
// Usage: Import and call seedDatabase() from browser console

import { db } from './firebase'
import { collection, addDoc, serverTimestamp } from 'firebase/firestore'

const testInternships = [
  {
    title: 'Software Development Intern',
    company: 'TechVasavi Solutions',
    employerUid: 'test-employer-1',
    employerName: 'Rajesh Kumar',
    location: 'Remote',
    type: 'Full-time',
    duration: '3 months',
    stipend: '$1,500/month',
    skills: ['React', 'Node.js', 'JavaScript', 'Git'],
    description: 'Join our development team to build modern web applications. You will work on real projects, collaborate with senior developers, and gain hands-on experience with cutting-edge technologies. This is a great opportunity for high school and college students interested in software engineering.',
    requirements: 'Currently in 11th grade or above. Basic knowledge of web development. Willingness to learn.',
    gradeLevelMin: '11th Grade',
    gradeLevelMax: 'College Senior',
    deadline: '2026-06-30',
    status: 'open',
    positions: 3,
    expectedHoursPerDay: '6-8 hours',
    contactEmail: 'rajesh@techvasavi.com',
  },
  {
    title: 'Data Analytics Intern',
    company: 'DataBridge Corp',
    employerUid: 'test-employer-2',
    employerName: 'Priya Reddy',
    location: 'New York, NY',
    type: 'Part-time',
    duration: '6 months',
    stipend: '$1,200/month',
    skills: ['Python', 'SQL', 'Tableau', 'Excel'],
    description: 'Analyze datasets to derive insights for our clients. Work with our analytics team on real business problems and develop your data analysis skills. Perfect for college students studying data science or business.',
    requirements: 'College Freshman or above. Familiarity with Python or Excel. Basic statistics knowledge.',
    gradeLevelMin: 'College Freshman',
    gradeLevelMax: 'College Senior',
    deadline: '2026-05-31',
    status: 'open',
    positions: 2,
    expectedHoursPerDay: '4-6 hours',
    contactEmail: 'priya@databridge.com',
  },
  {
    title: 'Marketing & Social Media Intern',
    company: 'NRIVA Foundation',
    employerUid: 'test-employer-3',
    employerName: 'Lakshmi Devi',
    location: 'Remote',
    type: 'Part-time',
    duration: '4 months',
    stipend: 'Unpaid (Volunteer)',
    skills: ['Social Media', 'Content Writing', 'Canva', 'Marketing'],
    description: 'Help NRIVA expand its digital presence through social media campaigns, content creation, and event promotion. Great for creative high schoolers wanting real-world marketing experience.',
    requirements: 'Strong communication skills. Active on social media platforms. 10th grade or above.',
    gradeLevelMin: '10th Grade',
    gradeLevelMax: 'College Senior',
    deadline: '2026-07-15',
    status: 'open',
    positions: 2,
    expectedHoursPerDay: '2-4 hours',
    contactEmail: 'lakshmi@nriva.org',
  },
  {
    title: 'Cloud Engineering Intern',
    company: 'CloudNine Technologies',
    employerUid: 'test-employer-4',
    employerName: 'Venkat Rao',
    location: 'San Francisco, CA',
    type: 'Full-time',
    duration: '3 months',
    stipend: '$2,000/month',
    skills: ['Azure', 'AWS', 'Docker', 'Linux'],
    description: 'Work with our cloud infrastructure team to design, deploy, and maintain cloud solutions. Ideal for college students pursuing CS/IT with interest in cloud computing.',
    requirements: 'College Sophomore or above. Basic understanding of cloud computing. Interest in DevOps.',
    gradeLevelMin: 'College Sophomore',
    gradeLevelMax: 'College Senior',
    deadline: '2026-05-15',
    status: 'open',
    positions: 2,
    expectedHoursPerDay: '6-8 hours',
    contactEmail: 'venkat@cloudnine.io',
  },
  {
    title: 'Graphic Design Intern',
    company: 'CreativeVasavi Studio',
    employerUid: 'test-employer-1',
    employerName: 'Anita Sharma',
    location: 'Remote',
    type: 'Part-time',
    duration: '3 months',
    stipend: '$800/month',
    skills: ['Adobe Photoshop', 'Illustrator', 'Figma', 'UI/UX'],
    description: 'Create visual assets for marketing campaigns, product designs, and brand materials. Open to artistic high schoolers and college students with a design portfolio.',
    requirements: 'Portfolio of design work (school projects count!). Basic knowledge of any design tool. 10th grade or above.',
    gradeLevelMin: '10th Grade',
    gradeLevelMax: 'College Senior',
    deadline: '2026-06-01',
    status: 'open',
    positions: 1,
    expectedHoursPerDay: '2-4 hours',
    contactEmail: 'anita@creativevasavi.com',
  },
  {
    title: 'Finance & Accounting Intern',
    company: 'NRIVA Foundation',
    employerUid: 'test-employer-3',
    employerName: 'Suresh Patel',
    location: 'Houston, TX',
    type: 'Full-time',
    duration: '6 months',
    stipend: '$1,300/month',
    skills: ['Excel', 'Financial Analysis', 'Accounting', 'QuickBooks'],
    description: 'Support the finance team with bookkeeping, financial reporting, and budget analysis. Great for college students studying finance or business administration.',
    requirements: 'College Freshman or above. Interest in finance/accounting. Proficiency in Excel.',
    gradeLevelMin: 'College Freshman',
    gradeLevelMax: 'College Senior',
    deadline: '2026-05-30',
    status: 'open',
    positions: 1,
    expectedHoursPerDay: '6-8 hours',
    contactEmail: 'suresh@nriva.org',
  },
  {
    title: 'Mobile App Development Intern',
    company: 'AppVasavi Labs',
    employerUid: 'test-employer-2',
    employerName: 'Kiran Desai',
    location: 'Remote',
    type: 'Full-time',
    duration: '3 months',
    stipend: '$1,800/month',
    skills: ['React Native', 'Flutter', 'iOS', 'Android'],
    description: 'Build mobile applications from scratch. Learn modern app development with mentorship from senior engineers. Perfect for students who want to see their code on phones.',
    requirements: '12th Grade or above. Some programming experience (any language). Enthusiasm for mobile apps.',
    gradeLevelMin: '12th Grade',
    gradeLevelMax: 'College Senior',
    deadline: '2026-06-15',
    status: 'open',
    positions: 2,
    expectedHoursPerDay: '6-8 hours',
    contactEmail: 'kiran@appvasavi.com',
  },
  {
    title: 'Environmental Research Intern',
    company: 'GreenFuture Initiative',
    employerUid: 'test-employer-4',
    employerName: 'Deepa Nair',
    location: 'Austin, TX',
    type: 'Part-time',
    duration: '4 months',
    stipend: '$1,000/month',
    skills: ['Research', 'Data Collection', 'Writing', 'Science'],
    description: 'Assist with environmental research projects including data collection, analysis, and report writing. Great for students passionate about science and sustainability.',
    requirements: '11th Grade or above. Interest in environmental science. Good writing skills.',
    gradeLevelMin: '11th Grade',
    gradeLevelMax: 'College Senior',
    deadline: '2026-07-01',
    status: 'open',
    positions: 3,
    expectedHoursPerDay: '4-6 hours',
    contactEmail: 'deepa@greenfuture.org',
  },
  {
    title: 'Healthcare Administration Intern',
    company: 'Vasavi Health Systems',
    employerUid: 'test-employer-1',
    employerName: 'Dr. Ramesh Gupta',
    location: 'Chicago, IL',
    type: 'Full-time',
    duration: '3 months',
    stipend: '$1,400/month',
    skills: ['Healthcare', 'Administration', 'Communication', 'Data Entry'],
    description: 'Learn about healthcare operations, patient management systems, and medical office workflows. Ideal for pre-med or health sciences students.',
    requirements: 'College Freshman or above. Interest in healthcare field. Strong organizational skills.',
    gradeLevelMin: 'College Freshman',
    gradeLevelMax: 'College Senior',
    deadline: '2026-06-01',
    status: 'open',
    positions: 2,
    expectedHoursPerDay: '6-8 hours',
    contactEmail: 'ramesh@vasavihealth.com',
  },
  {
    title: 'Journalism & Content Writing Intern',
    company: 'NRIVA Media',
    employerUid: 'test-employer-3',
    employerName: 'Meena Krishnamurthy',
    location: 'Remote',
    type: 'Part-time',
    duration: '3 months',
    stipend: 'Unpaid (Volunteer)',
    skills: ['Writing', 'Journalism', 'Editing', 'WordPress'],
    description: 'Write articles, interview community members, and help manage NRIVA\'s newsletter and blog. Build a real published portfolio while telling meaningful stories.',
    requirements: '10th Grade or above. Strong writing skills (samples required). Interest in journalism or communications.',
    gradeLevelMin: '10th Grade',
    gradeLevelMax: 'College Senior',
    deadline: '2026-07-31',
    status: 'open',
    positions: 3,
    expectedHoursPerDay: '2-4 hours',
    contactEmail: 'meena@nrivamedia.org',
  },
]

const testApplications = [
  {
    internshipTitle: 'Software Development Intern',
    company: 'TechVasavi Solutions',
    applicantUid: 'test-intern-1',
    applicantName: 'Arjun Naidu',
    email: 'arjun.naidu@email.com',
    phone: '(555) 123-4567',
    gradeLevel: 'College Junior',
    school: 'University of Texas at Austin',
    major: 'Computer Science',
    gpa: '3.7',
    status: 'under_review',
    chapter: 'Austin',
  },
  {
    internshipTitle: 'Software Development Intern',
    company: 'TechVasavi Solutions',
    applicantUid: 'test-intern-2',
    applicantName: 'Sneha Reddy',
    email: 'sneha.r@email.com',
    phone: '(555) 234-5678',
    gradeLevel: 'College Senior',
    school: 'Georgia Tech',
    major: 'Information Technology',
    gpa: '3.9',
    status: 'shortlisted',
    chapter: 'Atlanta',
  },
  {
    internshipTitle: 'Data Analytics Intern',
    company: 'DataBridge Corp',
    applicantUid: 'test-intern-3',
    applicantName: 'Vikram Patel',
    email: 'vikram.p@email.com',
    phone: '(555) 345-6789',
    gradeLevel: 'College Sophomore',
    school: 'NYU',
    major: 'Data Science',
    gpa: '3.5',
    status: 'accepted',
    chapter: 'New York',
  },
  {
    internshipTitle: 'Marketing & Social Media Intern',
    company: 'NRIVA Foundation',
    applicantUid: 'test-intern-4',
    applicantName: 'Meera Krishnan',
    email: 'meera.k@email.com',
    phone: '(555) 456-7890',
    gradeLevel: '11th Grade',
    school: 'Plano West Senior High',
    major: 'Communications',
    gpa: '3.6',
    status: 'pending',
    chapter: 'Dallas',
  },
  {
    internshipTitle: 'Graphic Design Intern',
    company: 'CreativeVasavi Studio',
    applicantUid: 'test-intern-5',
    applicantName: 'Ravi Teja',
    email: 'ravi.t@email.com',
    phone: '(555) 567-8901',
    gradeLevel: 'College Junior',
    school: 'SCAD',
    major: 'Graphic Design',
    gpa: '3.8',
    status: 'pending',
    chapter: 'Atlanta',
  },
  {
    internshipTitle: 'Mobile App Development Intern',
    company: 'AppVasavi Labs',
    applicantUid: 'test-intern-6',
    applicantName: 'Priya Venkat',
    email: 'priya.v@email.com',
    phone: '(555) 678-9012',
    gradeLevel: '12th Grade',
    school: 'Thomas Jefferson High School',
    major: 'Computer Science',
    gpa: '4.0',
    status: 'under_review',
    chapter: 'Virginia',
  },
  {
    internshipTitle: 'Environmental Research Intern',
    company: 'GreenFuture Initiative',
    applicantUid: 'test-intern-7',
    applicantName: 'Ananya Sharma',
    email: 'ananya.s@email.com',
    phone: '(555) 789-0123',
    gradeLevel: 'College Freshman',
    school: 'UT Austin',
    major: 'Environmental Science',
    gpa: '3.4',
    status: 'pending',
    chapter: 'Austin',
  },
  {
    internshipTitle: 'Cloud Engineering Intern',
    company: 'CloudNine Technologies',
    applicantUid: 'test-intern-8',
    applicantName: 'Siddharth Rao',
    email: 'sid.rao@email.com',
    phone: '(555) 890-1234',
    gradeLevel: 'College Senior',
    school: 'UC Berkeley',
    major: 'Computer Engineering',
    gpa: '3.6',
    status: 'shortlisted',
    chapter: 'San Francisco',
  },
  {
    internshipTitle: 'Finance & Accounting Intern',
    company: 'NRIVA Foundation',
    applicantUid: 'test-intern-9',
    applicantName: 'Kavya Desai',
    email: 'kavya.d@email.com',
    phone: '(555) 901-2345',
    gradeLevel: 'College Junior',
    school: 'University of Houston',
    major: 'Finance',
    gpa: '3.7',
    status: 'accepted',
    chapter: 'Houston',
  },
  {
    internshipTitle: 'Journalism & Content Writing Intern',
    company: 'NRIVA Media',
    applicantUid: 'test-intern-10',
    applicantName: 'Rohan Iyer',
    email: 'rohan.i@email.com',
    phone: '(555) 012-3456',
    gradeLevel: '10th Grade',
    school: 'Westwood High School',
    major: 'English / Journalism',
    gpa: '3.9',
    status: 'pending',
    chapter: 'Austin',
  },
]

export async function seedDatabase() {
  console.log('Seeding internships...')
  for (const internship of testInternships) {
    const ref = await addDoc(collection(db, 'internships'), {
      ...internship,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    })
    console.log(`  Created internship: ${internship.title} (${ref.id})`)
  }

  console.log('Seeding applications...')
  for (const app of testApplications) {
    const ref = await addDoc(collection(db, 'applications'), {
      ...app,
      appliedDate: serverTimestamp(),
    })
    console.log(`  Created application: ${app.applicantName} (${ref.id})`)
  }

  console.log('Seed complete! 10 internships + 10 applications created.')
}

// Make available globally for browser console
if (typeof window !== 'undefined') {
  window.seedDatabase = seedDatabase
}
